export const environment = {
  production: true,
  apiGoogleEndpoint: 'http://localhost:8080/api/google/:isbn',
  apiBookEndpointId: 'http://localhost:8080/api/book/:id',
  apiBookEndpoint: 'http://localhost:8080/api/book',
  apiAuthorEndpointId: 'http://localhost:8080/api/author/:id',
  apiAuthorEndpoint: 'http://localhost:8080/api/author',
  apiCourseEndpointId: 'http://localhost:8080/api/course/:id',
  apiCourseEndpoint: 'http://localhost:8080/api/course',
  apiPublisherEndpointId: 'http://localhost:8080/api/publisher/:id',
  apiPublisherEndpoint: 'http://localhost:8080/api/publisher',
  apiTagEndpointId: 'http://localhost:8080/api/tag/:tag',
  apiTagEndpoint: 'http://localhost:8080/api/tag',
  apiFileEndpointId: 'http://localhost:8080/api/file/:id',
  apiFileEndpoint: 'http://localhost:8080/api/file',
  apiDescriptEndpointId: 'http://localhost:8080/api/descript/:id',
  apiDescriptEndpoint: 'http://localhost:8080/api/descript',
  apiInfoEndpointId: 'http://localhost:8080/api/info/:id',
  apiInfoEndpoint: 'http://localhost:8080/api/info'
};
