export const environment = {
  production: true,
  apiGoogleEndpoint: '/api/google/:isbn',
  apiBookEndpointId: '/api/book/:id',
  apiBookEndpoint: '/api/book',
  apiAuthorEndpointId: '/api/author/:id',
  apiAuthorEndpoint: '/api/author',
  apiCourseEndpointId: '/api/course/:id',
  apiCourseEndpoint: '/api/course',
  apiPublisherEndpointId: '/api/publisher/:id',
  apiPublisherEndpoint: '/api/publisher',
  apiTagEndpointId: '/api/tag/:tag',
  apiTagEndpoint: '/api/tag',
  apiFileEndpointId: '/api/file/:id',
  apiFileEndpoint: '/api/file',
  apiDescriptEndpointId: '/api/descript/:id',
  apiDescriptEndpoint: '/api/descript',
  apiInfoEndpointId: '/api/info/:id',
  apiInfoEndpoint: '/api/info'
};
